#ifndef QUICKGUISCROLLBARBUTTONTYPES_H
#define QUICKGUISCROLLBARBUTTONTYPES_H

namespace QuickGUI
{
	enum VScrollBarButtonLayout
	{
		VSCROLL_BAR_BUTTON_LAYOUT_ADJACENT_UP		=  0,
		VSCROLL_BAR_BUTTON_LAYOUT_ADJACENT_DOWN			,
		VSCROLL_BAR_BUTTON_LAYOUT_MULTIPLE_BOTH			,
		VSCROLL_BAR_BUTTON_LAYOUT_MULTIPLE_UP			,
		VSCROLL_BAR_BUTTON_LAYOUT_MULTIPLE_DOWN			,
		VSCROLL_BAR_BUTTON_LAYOUT_NONE					,
		VSCROLL_BAR_BUTTON_LAYOUT_OPPOSITE			
	};

	enum HScrollBarButtonLayout
	{
		HSCROLL_BAR_BUTTON_LAYOUT_ADJACENT_LEFT		=  0,
		HSCROLL_BAR_BUTTON_LAYOUT_ADJACENT_RIGHT		,
		HSCROLL_BAR_BUTTON_LAYOUT_MULTIPLE_BOTH			,
		HSCROLL_BAR_BUTTON_LAYOUT_MULTIPLE_LEFT			,
		HSCROLL_BAR_BUTTON_LAYOUT_MULTIPLE_RIGHT		,
		HSCROLL_BAR_BUTTON_LAYOUT_NONE					,
		HSCROLL_BAR_BUTTON_LAYOUT_OPPOSITE			
	};
}

#endif
